//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VSCustomElement {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HtmAttributes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HtmAttributes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VSCustomElement.HtmAttributes", typeof(HtmAttributes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to charset,coords,download,href,hreflang,media,name,rel,rev,shape,target,type.
        /// </summary>
        internal static string _a {
            get {
                return ResourceManager.GetString("_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _abbr {
            get {
                return ResourceManager.GetString("_abbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _acronym {
            get {
                return ResourceManager.GetString("_acronym", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _address {
            get {
                return ResourceManager.GetString("_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to code,object,align,alt,archive,codebase,height,hspace,name,vspace,width.
        /// </summary>
        internal static string _applet {
            get {
                return ResourceManager.GetString("_applet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alt,coords,download,href,hreflang,media,nohref,rel,shape,target,type.
        /// </summary>
        internal static string _area {
            get {
                return ResourceManager.GetString("_area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _article {
            get {
                return ResourceManager.GetString("_article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _aside {
            get {
                return ResourceManager.GetString("_aside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to autoplay,controls,loop,muted,preload,src.
        /// </summary>
        internal static string _audio {
            get {
                return ResourceManager.GetString("_audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _b {
            get {
                return ResourceManager.GetString("_b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to href,target.
        /// </summary>
        internal static string _base {
            get {
                return ResourceManager.GetString("_base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to color,face,size.
        /// </summary>
        internal static string _basefont {
            get {
                return ResourceManager.GetString("_basefont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _bdi {
            get {
                return ResourceManager.GetString("_bdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dir.
        /// </summary>
        internal static string _bdo {
            get {
                return ResourceManager.GetString("_bdo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _big {
            get {
                return ResourceManager.GetString("_big", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cite.
        /// </summary>
        internal static string _blockquote {
            get {
                return ResourceManager.GetString("_blockquote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alink,background,bgcolor,link,text,vlink.
        /// </summary>
        internal static string _body {
            get {
                return ResourceManager.GetString("_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _br {
            get {
                return ResourceManager.GetString("_br", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to autofocus, disabled,form,formaction,formenctype,formmethod,formtarget,name,type,value.
        /// </summary>
        internal static string _button {
            get {
                return ResourceManager.GetString("_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to height,width.
        /// </summary>
        internal static string _canvas {
            get {
                return ResourceManager.GetString("_canvas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to align.
        /// </summary>
        internal static string _caption {
            get {
                return ResourceManager.GetString("_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _center {
            get {
                return ResourceManager.GetString("_center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _cite {
            get {
                return ResourceManager.GetString("_cite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _code {
            get {
                return ResourceManager.GetString("_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to align,char,charoff,span,valign,width.
        /// </summary>
        internal static string _col {
            get {
                return ResourceManager.GetString("_col", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to align,char,charoff,span,valign,width.
        /// </summary>
        internal static string _colgroup {
            get {
                return ResourceManager.GetString("_colgroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _datalist {
            get {
                return ResourceManager.GetString("_datalist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _dd {
            get {
                return ResourceManager.GetString("_dd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cite,datetime.
        /// </summary>
        internal static string _del {
            get {
                return ResourceManager.GetString("_del", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to open.
        /// </summary>
        internal static string _details {
            get {
                return ResourceManager.GetString("_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _dfn {
            get {
                return ResourceManager.GetString("_dfn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to open.
        /// </summary>
        internal static string _dialog {
            get {
                return ResourceManager.GetString("_dialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to compact.
        /// </summary>
        internal static string _dir {
            get {
                return ResourceManager.GetString("_dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to align.
        /// </summary>
        internal static string _div {
            get {
                return ResourceManager.GetString("_div", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _dl {
            get {
                return ResourceManager.GetString("_dl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _dt {
            get {
                return ResourceManager.GetString("_dt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _em {
            get {
                return ResourceManager.GetString("_em", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _embed {
            get {
                return ResourceManager.GetString("_embed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hright,src,type,width.
        /// </summary>
        internal static string _fieldset {
            get {
                return ResourceManager.GetString("_fieldset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _figcaption {
            get {
                return ResourceManager.GetString("_figcaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _figure {
            get {
                return ResourceManager.GetString("_figure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to color,face,size.
        /// </summary>
        internal static string _font {
            get {
                return ResourceManager.GetString("_font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _footer {
            get {
                return ResourceManager.GetString("_footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to accept,accept-charset,action,autocomplete,enctype,method,name,novalidate,target.
        /// </summary>
        internal static string _form {
            get {
                return ResourceManager.GetString("_form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frameborder,longdesc,marginheight,marginwidthiname,noresize,scrolling,src.
        /// </summary>
        internal static string _frame {
            get {
                return ResourceManager.GetString("_frame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cols,rows.
        /// </summary>
        internal static string _frameset {
            get {
                return ResourceManager.GetString("_frameset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to align.
        /// </summary>
        internal static string _h1 {
            get {
                return ResourceManager.GetString("_h1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to align.
        /// </summary>
        internal static string _h2 {
            get {
                return ResourceManager.GetString("_h2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to align.
        /// </summary>
        internal static string _h3 {
            get {
                return ResourceManager.GetString("_h3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to align.
        /// </summary>
        internal static string _h4 {
            get {
                return ResourceManager.GetString("_h4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to align.
        /// </summary>
        internal static string _h5 {
            get {
                return ResourceManager.GetString("_h5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to align.
        /// </summary>
        internal static string _h6 {
            get {
                return ResourceManager.GetString("_h6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to profile.
        /// </summary>
        internal static string _head {
            get {
                return ResourceManager.GetString("_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _header {
            get {
                return ResourceManager.GetString("_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to align,noshade,size,width.
        /// </summary>
        internal static string _hr {
            get {
                return ResourceManager.GetString("_hr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to manifest,xmlns.
        /// </summary>
        internal static string _html {
            get {
                return ResourceManager.GetString("_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _i {
            get {
                return ResourceManager.GetString("_i", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to align,frameborder,height,longdesc,marginheight,marginwidth,name,sandbox,scrolling,src,srcdoc,width.
        /// </summary>
        internal static string _iframe {
            get {
                return ResourceManager.GetString("_iframe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to align,alt,border,crossorigin,height,hspace,ismap,longdesc,src,usemap,vspace,width.
        /// </summary>
        internal static string _img {
            get {
                return ResourceManager.GetString("_img", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to accept,align,alt,autocomplete,autofocus,checked,dirname,disabled,form,formaction,formenctype,formmethod,formnovalidate,formtarget,height,list,max,maxlength,min,multiple,name,pattern,placeholder,readonly,required,size,src,step,type,value,width.
        /// </summary>
        internal static string _input {
            get {
                return ResourceManager.GetString("_input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cite,datetime.
        /// </summary>
        internal static string _ins {
            get {
                return ResourceManager.GetString("_ins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _kbd {
            get {
                return ResourceManager.GetString("_kbd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to autofocus,challange,disabled,form,keytype,name.
        /// </summary>
        internal static string _keygen {
            get {
                return ResourceManager.GetString("_keygen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for,form.
        /// </summary>
        internal static string _label {
            get {
                return ResourceManager.GetString("_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to align.
        /// </summary>
        internal static string _legend {
            get {
                return ResourceManager.GetString("_legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to type,value.
        /// </summary>
        internal static string _li {
            get {
                return ResourceManager.GetString("_li", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to charset,crossorigin,href,media,rel,rev,sizes,target,type.
        /// </summary>
        internal static string _link {
            get {
                return ResourceManager.GetString("_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _main {
            get {
                return ResourceManager.GetString("_main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        internal static string _map {
            get {
                return ResourceManager.GetString("_map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _mark {
            get {
                return ResourceManager.GetString("_mark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to label,type.
        /// </summary>
        internal static string _menu {
            get {
                return ResourceManager.GetString("_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to checked,command,default,disabled,icon,label,radiogroup,type.
        /// </summary>
        internal static string _menuitem {
            get {
                return ResourceManager.GetString("_menuitem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to charset,content,http-equiv,name,scheme.
        /// </summary>
        internal static string _meta {
            get {
                return ResourceManager.GetString("_meta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to form,high,low,max,min,optimum,value.
        /// </summary>
        internal static string _meter {
            get {
                return ResourceManager.GetString("_meter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _nav {
            get {
                return ResourceManager.GetString("_nav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _noframes {
            get {
                return ResourceManager.GetString("_noframes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _noscript {
            get {
                return ResourceManager.GetString("_noscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to align,archive,border,classid,codebase,data,declare,form,height,hspace,name,standby,type,usemap,vspace,width.
        /// </summary>
        internal static string _object {
            get {
                return ResourceManager.GetString("_object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to compact,reversed,start,type.
        /// </summary>
        internal static string _ol {
            get {
                return ResourceManager.GetString("_ol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to disabled,label.
        /// </summary>
        internal static string _optgroup {
            get {
                return ResourceManager.GetString("_optgroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to disabled,label,selected,value.
        /// </summary>
        internal static string _option {
            get {
                return ResourceManager.GetString("_option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for,form,name.
        /// </summary>
        internal static string _output {
            get {
                return ResourceManager.GetString("_output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to align.
        /// </summary>
        internal static string _p {
            get {
                return ResourceManager.GetString("_p", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name,type,value,valuetype.
        /// </summary>
        internal static string _param {
            get {
                return ResourceManager.GetString("_param", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to width.
        /// </summary>
        internal static string _pre {
            get {
                return ResourceManager.GetString("_pre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to max,value.
        /// </summary>
        internal static string _progress {
            get {
                return ResourceManager.GetString("_progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cite.
        /// </summary>
        internal static string _q {
            get {
                return ResourceManager.GetString("_q", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _rp {
            get {
                return ResourceManager.GetString("_rp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _rt {
            get {
                return ResourceManager.GetString("_rt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _ruby {
            get {
                return ResourceManager.GetString("_ruby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _s {
            get {
                return ResourceManager.GetString("_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _samp {
            get {
                return ResourceManager.GetString("_samp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to async,charset,defer,src,type,xml:space.
        /// </summary>
        internal static string _script {
            get {
                return ResourceManager.GetString("_script", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _section {
            get {
                return ResourceManager.GetString("_section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to autofocus,disabled,form,multiple,name,required,size.
        /// </summary>
        internal static string _select {
            get {
                return ResourceManager.GetString("_select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _small {
            get {
                return ResourceManager.GetString("_small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to media,src,type.
        /// </summary>
        internal static string _source {
            get {
                return ResourceManager.GetString("_source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _span {
            get {
                return ResourceManager.GetString("_span", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _strike {
            get {
                return ResourceManager.GetString("_strike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _strong {
            get {
                return ResourceManager.GetString("_strong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to media,scoped,type.
        /// </summary>
        internal static string _style {
            get {
                return ResourceManager.GetString("_style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _sub {
            get {
                return ResourceManager.GetString("_sub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _summary {
            get {
                return ResourceManager.GetString("_summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _sup {
            get {
                return ResourceManager.GetString("_sup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to align,bgcolor,border,cellpadding,cellspacing,frame,rules,sortable,summary,width.
        /// </summary>
        internal static string _table {
            get {
                return ResourceManager.GetString("_table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to align,char,charoff,valign.
        /// </summary>
        internal static string _tbody {
            get {
                return ResourceManager.GetString("_tbody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abbr,align,axis,bgcolor,char,charoff,colspan,headers,height,nowrap,rowspan,scope,valign,width.
        /// </summary>
        internal static string _td {
            get {
                return ResourceManager.GetString("_td", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to autofocus,cols,dirname,disabled,form,maxlength,name,placeholder,readonly,required,rows,wrap.
        /// </summary>
        internal static string _textarea {
            get {
                return ResourceManager.GetString("_textarea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to align,char,charoff,valign.
        /// </summary>
        internal static string _tfoot {
            get {
                return ResourceManager.GetString("_tfoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abbr,align,axis,bgcolor,char,charoff,colspan,headers,height,nowrap,rowspan,scope,valign,width,sorted.
        /// </summary>
        internal static string _th {
            get {
                return ResourceManager.GetString("_th", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to align,char,charoff,valign.
        /// </summary>
        internal static string _thead {
            get {
                return ResourceManager.GetString("_thead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to datetime.
        /// </summary>
        internal static string _time {
            get {
                return ResourceManager.GetString("_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _title {
            get {
                return ResourceManager.GetString("_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to align,char,charoff,valign,bgcolor.
        /// </summary>
        internal static string _tr {
            get {
                return ResourceManager.GetString("_tr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to default,kind,label,src,srclang.
        /// </summary>
        internal static string _track {
            get {
                return ResourceManager.GetString("_track", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _tt {
            get {
                return ResourceManager.GetString("_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _u {
            get {
                return ResourceManager.GetString("_u", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to compact,type.
        /// </summary>
        internal static string _ul {
            get {
                return ResourceManager.GetString("_ul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _var {
            get {
                return ResourceManager.GetString("_var", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to autoplay,controls,height,loop,muted,poster,preload,src,width.
        /// </summary>
        internal static string _video {
            get {
                return ResourceManager.GetString("_video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _wbr {
            get {
                return ResourceManager.GetString("_wbr", resourceCulture);
            }
        }
    }
}
